# Setup
title:        akatsuki akira's home
tagline:      one percent inspiration and 99 percent perspiration.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       akatsuki akira
  url:        https://akatsukiakira.me

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
